# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", "vaultshare") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "vaultshare_development") %>

test:
  <<: *default
  database: vaultshare_test

production:
  primary: &primary_production
    <<: *default
    database: vaultshare_production
    username: vaultshare
    password: <%= ENV["VAULTSHARE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: vaultshare_production_cache
    migrations_paths: db/cache_migrate
  cable:
    <<: *primary_production
    database: vaultshare_production_cable
    migrations_paths: db/cable_migrate
